//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALEntityMedecin
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    using SqlProviderServices = System.Data.Entity.SqlServer.SqlProviderServices;
    public partial class MedAssistV2Entities : DbContext
    {
        public MedAssistV2Entities()
            : base(ConnectionStringMed.GetEFConnectionString())
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<SelectPlanningMedecin_Result> SelectPlanningMedecin(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectPlanningMedecin_Result>("SelectPlanningMedecin", idParameter);
        }
    
        public virtual ObjectResult<SelectTest_Result> SelectTest()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectTest_Result>("SelectTest");
        }
    
        public virtual ObjectResult<SelectMedecin_Result> SelectMedecin(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectMedecin_Result>("SelectMedecin", idParameter);
        }
    
        public virtual int AddPlanningMedecin(Nullable<System.DateTime> jourDePresence, Nullable<System.TimeSpan> heureDebutmatin, Nullable<System.TimeSpan> heurefinmatin, Nullable<System.TimeSpan> heureDebutAprem, Nullable<System.TimeSpan> heureFinAprem, Nullable<int> iDmaison, Nullable<int> iDMedecin)
        {
            var jourDePresenceParameter = jourDePresence.HasValue ?
                new ObjectParameter("jourDePresence", jourDePresence) :
                new ObjectParameter("jourDePresence", typeof(System.DateTime));
    
            var heureDebutmatinParameter = heureDebutmatin.HasValue ?
                new ObjectParameter("HeureDebutmatin", heureDebutmatin) :
                new ObjectParameter("HeureDebutmatin", typeof(System.TimeSpan));
    
            var heurefinmatinParameter = heurefinmatin.HasValue ?
                new ObjectParameter("heurefinmatin", heurefinmatin) :
                new ObjectParameter("heurefinmatin", typeof(System.TimeSpan));
    
            var heureDebutApremParameter = heureDebutAprem.HasValue ?
                new ObjectParameter("heureDebutAprem", heureDebutAprem) :
                new ObjectParameter("heureDebutAprem", typeof(System.TimeSpan));
    
            var heureFinApremParameter = heureFinAprem.HasValue ?
                new ObjectParameter("heureFinAprem", heureFinAprem) :
                new ObjectParameter("heureFinAprem", typeof(System.TimeSpan));
    
            var iDmaisonParameter = iDmaison.HasValue ?
                new ObjectParameter("IDmaison", iDmaison) :
                new ObjectParameter("IDmaison", typeof(int));
    
            var iDMedecinParameter = iDMedecin.HasValue ?
                new ObjectParameter("IDMedecin", iDMedecin) :
                new ObjectParameter("IDMedecin", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddPlanningMedecin", jourDePresenceParameter, heureDebutmatinParameter, heurefinmatinParameter, heureDebutApremParameter, heureFinApremParameter, iDmaisonParameter, iDMedecinParameter);
        }
    
        public virtual ObjectResult<SelectMaisonMedecin_Result> SelectMaisonMedecin(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectMaisonMedecin_Result>("SelectMaisonMedecin", idParameter);
        }
    
        public virtual int deletePlanning(Nullable<int> idPlanning)
        {
            var idPlanningParameter = idPlanning.HasValue ?
                new ObjectParameter("IdPlanning", idPlanning) :
                new ObjectParameter("IdPlanning", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deletePlanning", idPlanningParameter);
        }
    
        public virtual int UpdatePlanningMedecin(Nullable<int> idPlanning, Nullable<System.TimeSpan> heureDebutmatin, Nullable<System.TimeSpan> heurefinmatin, Nullable<System.TimeSpan> heureDebutAprem, Nullable<System.TimeSpan> heureFinAprem)
        {
            var idPlanningParameter = idPlanning.HasValue ?
                new ObjectParameter("IdPlanning", idPlanning) :
                new ObjectParameter("IdPlanning", typeof(int));
    
            var heureDebutmatinParameter = heureDebutmatin.HasValue ?
                new ObjectParameter("HeureDebutmatin", heureDebutmatin) :
                new ObjectParameter("HeureDebutmatin", typeof(System.TimeSpan));
    
            var heurefinmatinParameter = heurefinmatin.HasValue ?
                new ObjectParameter("heurefinmatin", heurefinmatin) :
                new ObjectParameter("heurefinmatin", typeof(System.TimeSpan));
    
            var heureDebutApremParameter = heureDebutAprem.HasValue ?
                new ObjectParameter("heureDebutAprem", heureDebutAprem) :
                new ObjectParameter("heureDebutAprem", typeof(System.TimeSpan));
    
            var heureFinApremParameter = heureFinAprem.HasValue ?
                new ObjectParameter("heureFinAprem", heureFinAprem) :
                new ObjectParameter("heureFinAprem", typeof(System.TimeSpan));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdatePlanningMedecin", idPlanningParameter, heureDebutmatinParameter, heurefinmatinParameter, heureDebutApremParameter, heureFinApremParameter);
        }
    
        public virtual int AddSpecialite(Nullable<int> idMedecin, Nullable<int> iDMaison, Nullable<int> idSpecialite, Nullable<int> duree)
        {
            var idMedecinParameter = idMedecin.HasValue ?
                new ObjectParameter("IdMedecin", idMedecin) :
                new ObjectParameter("IdMedecin", typeof(int));
    
            var iDMaisonParameter = iDMaison.HasValue ?
                new ObjectParameter("IDMaison", iDMaison) :
                new ObjectParameter("IDMaison", typeof(int));
    
            var idSpecialiteParameter = idSpecialite.HasValue ?
                new ObjectParameter("IdSpecialite", idSpecialite) :
                new ObjectParameter("IdSpecialite", typeof(int));
    
            var dureeParameter = duree.HasValue ?
                new ObjectParameter("duree", duree) :
                new ObjectParameter("duree", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddSpecialite", idMedecinParameter, iDMaisonParameter, idSpecialiteParameter, dureeParameter);
        }
    
        public virtual int DeleteSpecialite(Nullable<int> idMedecin, Nullable<int> idMaison, Nullable<int> idSpecialite)
        {
            var idMedecinParameter = idMedecin.HasValue ?
                new ObjectParameter("IdMedecin", idMedecin) :
                new ObjectParameter("IdMedecin", typeof(int));
    
            var idMaisonParameter = idMaison.HasValue ?
                new ObjectParameter("IdMaison", idMaison) :
                new ObjectParameter("IdMaison", typeof(int));
    
            var idSpecialiteParameter = idSpecialite.HasValue ?
                new ObjectParameter("IdSpecialite", idSpecialite) :
                new ObjectParameter("IdSpecialite", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteSpecialite", idMedecinParameter, idMaisonParameter, idSpecialiteParameter);
        }
    
        public virtual ObjectResult<SelectSpecialiteMedecin_Result> SelectSpecialiteMedecin(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectSpecialiteMedecin_Result>("SelectSpecialiteMedecin", idParameter);
        }
    
        public virtual int UpdateSpecialite(Nullable<int> idMedecin, Nullable<int> idMaison, Nullable<int> idSpecialise, Nullable<int> duree)
        {
            var idMedecinParameter = idMedecin.HasValue ?
                new ObjectParameter("IdMedecin", idMedecin) :
                new ObjectParameter("IdMedecin", typeof(int));
    
            var idMaisonParameter = idMaison.HasValue ?
                new ObjectParameter("IdMaison", idMaison) :
                new ObjectParameter("IdMaison", typeof(int));
    
            var idSpecialiseParameter = idSpecialise.HasValue ?
                new ObjectParameter("IdSpecialise", idSpecialise) :
                new ObjectParameter("IdSpecialise", typeof(int));
    
            var dureeParameter = duree.HasValue ?
                new ObjectParameter("duree", duree) :
                new ObjectParameter("duree", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateSpecialite", idMedecinParameter, idMaisonParameter, idSpecialiseParameter, dureeParameter);
        }
    
        public virtual ObjectResult<SelectAllMedecin_Result> SelectAllMedecin(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectAllMedecin_Result>("SelectAllMedecin", idParameter);
        }
    
        public virtual ObjectResult<SelectAllSpecialite_Result> SelectAllSpecialite()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectAllSpecialite_Result>("SelectAllSpecialite");
        }
    
        public virtual ObjectResult<SelectAllMaison_Result> SelectAllMaison()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectAllMaison_Result>("SelectAllMaison");
        }
    
        public virtual ObjectResult<SelectMaisonBySpecialiteByMedecin_Result> SelectMaisonBySpecialiteByMedecin(Nullable<int> idm, Nullable<int> idSp)
        {
            var idmParameter = idm.HasValue ?
                new ObjectParameter("Idm", idm) :
                new ObjectParameter("Idm", typeof(int));
    
            var idSpParameter = idSp.HasValue ?
                new ObjectParameter("idSp", idSp) :
                new ObjectParameter("idSp", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectMaisonBySpecialiteByMedecin_Result>("SelectMaisonBySpecialiteByMedecin", idmParameter, idSpParameter);
        }
    
        public virtual int AddPlanningMedecin1(Nullable<System.DateTime> jourDePresence, Nullable<System.TimeSpan> heureDebutmatin, Nullable<System.TimeSpan> heurefinmatin, Nullable<System.TimeSpan> heureDebutAprem, Nullable<System.TimeSpan> heureFinAprem, Nullable<int> iDmaison, Nullable<int> iDMedecin)
        {
            var jourDePresenceParameter = jourDePresence.HasValue ?
                new ObjectParameter("jourDePresence", jourDePresence) :
                new ObjectParameter("jourDePresence", typeof(System.DateTime));
    
            var heureDebutmatinParameter = heureDebutmatin.HasValue ?
                new ObjectParameter("HeureDebutmatin", heureDebutmatin) :
                new ObjectParameter("HeureDebutmatin", typeof(System.TimeSpan));
    
            var heurefinmatinParameter = heurefinmatin.HasValue ?
                new ObjectParameter("heurefinmatin", heurefinmatin) :
                new ObjectParameter("heurefinmatin", typeof(System.TimeSpan));
    
            var heureDebutApremParameter = heureDebutAprem.HasValue ?
                new ObjectParameter("heureDebutAprem", heureDebutAprem) :
                new ObjectParameter("heureDebutAprem", typeof(System.TimeSpan));
    
            var heureFinApremParameter = heureFinAprem.HasValue ?
                new ObjectParameter("heureFinAprem", heureFinAprem) :
                new ObjectParameter("heureFinAprem", typeof(System.TimeSpan));
    
            var iDmaisonParameter = iDmaison.HasValue ?
                new ObjectParameter("IDmaison", iDmaison) :
                new ObjectParameter("IDmaison", typeof(int));
    
            var iDMedecinParameter = iDMedecin.HasValue ?
                new ObjectParameter("IDMedecin", iDMedecin) :
                new ObjectParameter("IDMedecin", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddPlanningMedecin1", jourDePresenceParameter, heureDebutmatinParameter, heurefinmatinParameter, heureDebutApremParameter, heureFinApremParameter, iDmaisonParameter, iDMedecinParameter);
        }
    
        public virtual int AddSpecialite1(Nullable<int> idMedecin, Nullable<int> iDMaison, Nullable<int> idSpecialite, Nullable<int> duree)
        {
            var idMedecinParameter = idMedecin.HasValue ?
                new ObjectParameter("IdMedecin", idMedecin) :
                new ObjectParameter("IdMedecin", typeof(int));
    
            var iDMaisonParameter = iDMaison.HasValue ?
                new ObjectParameter("IDMaison", iDMaison) :
                new ObjectParameter("IDMaison", typeof(int));
    
            var idSpecialiteParameter = idSpecialite.HasValue ?
                new ObjectParameter("IdSpecialite", idSpecialite) :
                new ObjectParameter("IdSpecialite", typeof(int));
    
            var dureeParameter = duree.HasValue ?
                new ObjectParameter("duree", duree) :
                new ObjectParameter("duree", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddSpecialite1", idMedecinParameter, iDMaisonParameter, idSpecialiteParameter, dureeParameter);
        }
    
        public virtual int deletePlanning1(Nullable<int> idPlanning)
        {
            var idPlanningParameter = idPlanning.HasValue ?
                new ObjectParameter("IdPlanning", idPlanning) :
                new ObjectParameter("IdPlanning", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("deletePlanning1", idPlanningParameter);
        }
    
        public virtual int DeleteSpecialite1(Nullable<int> idMedecin, Nullable<int> idMaison, Nullable<int> idSpecialite)
        {
            var idMedecinParameter = idMedecin.HasValue ?
                new ObjectParameter("IdMedecin", idMedecin) :
                new ObjectParameter("IdMedecin", typeof(int));
    
            var idMaisonParameter = idMaison.HasValue ?
                new ObjectParameter("IdMaison", idMaison) :
                new ObjectParameter("IdMaison", typeof(int));
    
            var idSpecialiteParameter = idSpecialite.HasValue ?
                new ObjectParameter("IdSpecialite", idSpecialite) :
                new ObjectParameter("IdSpecialite", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteSpecialite1", idMedecinParameter, idMaisonParameter, idSpecialiteParameter);
        }
    
        public virtual ObjectResult<SelectAllMaison1_Result> SelectAllMaison1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectAllMaison1_Result>("SelectAllMaison1");
        }
    
        public virtual ObjectResult<SelectAllSpecialite1_Result> SelectAllSpecialite1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectAllSpecialite1_Result>("SelectAllSpecialite1");
        }
    
        public virtual ObjectResult<SelectConsultationMedecin_Result> SelectConsultationMedecin(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectConsultationMedecin_Result>("SelectConsultationMedecin", idParameter);
        }
    
        public virtual ObjectResult<SelectMaisonBySpecialiteByMedecin1_Result> SelectMaisonBySpecialiteByMedecin1(Nullable<int> idm, Nullable<int> idSp)
        {
            var idmParameter = idm.HasValue ?
                new ObjectParameter("Idm", idm) :
                new ObjectParameter("Idm", typeof(int));
    
            var idSpParameter = idSp.HasValue ?
                new ObjectParameter("idSp", idSp) :
                new ObjectParameter("idSp", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectMaisonBySpecialiteByMedecin1_Result>("SelectMaisonBySpecialiteByMedecin1", idmParameter, idSpParameter);
        }
    
        public virtual ObjectResult<SelectMaisonMedecin1_Result> SelectMaisonMedecin1(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectMaisonMedecin1_Result>("SelectMaisonMedecin1", idParameter);
        }
    
        public virtual ObjectResult<SelectMedecin1_Result> SelectMedecin1(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectMedecin1_Result>("SelectMedecin1", idParameter);
        }
    
        public virtual ObjectResult<SelectPlanningMedecin1_Result> SelectPlanningMedecin1(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectPlanningMedecin1_Result>("SelectPlanningMedecin1", idParameter);
        }
    
        public virtual ObjectResult<SelectSpecialiteMedecin1_Result> SelectSpecialiteMedecin1(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectSpecialiteMedecin1_Result>("SelectSpecialiteMedecin1", idParameter);
        }
    
        public virtual ObjectResult<SelectTest1_Result> SelectTest1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectTest1_Result>("SelectTest1");
        }
    
        public virtual int UpdatePlanningMedecin1(Nullable<int> idPlanning, Nullable<System.TimeSpan> heureDebutmatin, Nullable<System.TimeSpan> heurefinmatin, Nullable<System.TimeSpan> heureDebutAprem, Nullable<System.TimeSpan> heureFinAprem)
        {
            var idPlanningParameter = idPlanning.HasValue ?
                new ObjectParameter("IdPlanning", idPlanning) :
                new ObjectParameter("IdPlanning", typeof(int));
    
            var heureDebutmatinParameter = heureDebutmatin.HasValue ?
                new ObjectParameter("HeureDebutmatin", heureDebutmatin) :
                new ObjectParameter("HeureDebutmatin", typeof(System.TimeSpan));
    
            var heurefinmatinParameter = heurefinmatin.HasValue ?
                new ObjectParameter("heurefinmatin", heurefinmatin) :
                new ObjectParameter("heurefinmatin", typeof(System.TimeSpan));
    
            var heureDebutApremParameter = heureDebutAprem.HasValue ?
                new ObjectParameter("heureDebutAprem", heureDebutAprem) :
                new ObjectParameter("heureDebutAprem", typeof(System.TimeSpan));
    
            var heureFinApremParameter = heureFinAprem.HasValue ?
                new ObjectParameter("heureFinAprem", heureFinAprem) :
                new ObjectParameter("heureFinAprem", typeof(System.TimeSpan));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdatePlanningMedecin1", idPlanningParameter, heureDebutmatinParameter, heurefinmatinParameter, heureDebutApremParameter, heureFinApremParameter);
        }
    
        public virtual int UpdateSpecialite1(Nullable<int> idMedecin, Nullable<int> idMaison, Nullable<int> idSpecialise, Nullable<int> duree)
        {
            var idMedecinParameter = idMedecin.HasValue ?
                new ObjectParameter("IdMedecin", idMedecin) :
                new ObjectParameter("IdMedecin", typeof(int));
    
            var idMaisonParameter = idMaison.HasValue ?
                new ObjectParameter("IdMaison", idMaison) :
                new ObjectParameter("IdMaison", typeof(int));
    
            var idSpecialiseParameter = idSpecialise.HasValue ?
                new ObjectParameter("IdSpecialise", idSpecialise) :
                new ObjectParameter("IdSpecialise", typeof(int));
    
            var dureeParameter = duree.HasValue ?
                new ObjectParameter("duree", duree) :
                new ObjectParameter("duree", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateSpecialite1", idMedecinParameter, idMaisonParameter, idSpecialiseParameter, dureeParameter);
        }
    
        public virtual int UpdatePlanningMedecinApres(Nullable<int> idPlanning, Nullable<System.TimeSpan> heureDebutAprem, Nullable<System.TimeSpan> heureFinAprem)
        {
            var idPlanningParameter = idPlanning.HasValue ?
                new ObjectParameter("IdPlanning", idPlanning) :
                new ObjectParameter("IdPlanning", typeof(int));
    
            var heureDebutApremParameter = heureDebutAprem.HasValue ?
                new ObjectParameter("heureDebutAprem", heureDebutAprem) :
                new ObjectParameter("heureDebutAprem", typeof(System.TimeSpan));
    
            var heureFinApremParameter = heureFinAprem.HasValue ?
                new ObjectParameter("heureFinAprem", heureFinAprem) :
                new ObjectParameter("heureFinAprem", typeof(System.TimeSpan));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdatePlanningMedecinApres", idPlanningParameter, heureDebutApremParameter, heureFinApremParameter);
        }
    
        public virtual int UpdatePlanningMedecinMatin(Nullable<int> idPlanning, Nullable<System.TimeSpan> heureDebutmatin, Nullable<System.TimeSpan> heurefinmatin)
        {
            var idPlanningParameter = idPlanning.HasValue ?
                new ObjectParameter("IdPlanning", idPlanning) :
                new ObjectParameter("IdPlanning", typeof(int));
    
            var heureDebutmatinParameter = heureDebutmatin.HasValue ?
                new ObjectParameter("HeureDebutmatin", heureDebutmatin) :
                new ObjectParameter("HeureDebutmatin", typeof(System.TimeSpan));
    
            var heurefinmatinParameter = heurefinmatin.HasValue ?
                new ObjectParameter("heurefinmatin", heurefinmatin) :
                new ObjectParameter("heurefinmatin", typeof(System.TimeSpan));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdatePlanningMedecinMatin", idPlanningParameter, heureDebutmatinParameter, heurefinmatinParameter);
        }
    
        public virtual ObjectResult<SelectConsultationMedecinApresMidiDernier_Result> SelectConsultationMedecinApresMidiDernier(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectConsultationMedecinApresMidiDernier_Result>("SelectConsultationMedecinApresMidiDernier", idParameter);
        }
    
        public virtual ObjectResult<SelectConsultationMedecinApresMidiPremier_Result> SelectConsultationMedecinApresMidiPremier(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectConsultationMedecinApresMidiPremier_Result>("SelectConsultationMedecinApresMidiPremier", idParameter);
        }
    
        public virtual ObjectResult<SelectConsultationMedecinMatinDernier_Result> SelectConsultationMedecinMatinDernier(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectConsultationMedecinMatinDernier_Result>("SelectConsultationMedecinMatinDernier", idParameter);
        }
    
        public virtual ObjectResult<SelectConsultationMedecinMatinPremier_Result> SelectConsultationMedecinMatinPremier(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectConsultationMedecinMatinPremier_Result>("SelectConsultationMedecinMatinPremier", idParameter);
        }
    
        public virtual ObjectResult<SelectConsultationByIdPlanning_Result> SelectConsultationByIdPlanning(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectConsultationByIdPlanning_Result>("SelectConsultationByIdPlanning", idParameter);
        }
    
        public virtual int AddRConfirmation(Nullable<int> idRDV, Nullable<int> idMedecin, Nullable<int> confirme)
        {
            var idRDVParameter = idRDV.HasValue ?
                new ObjectParameter("idRDV", idRDV) :
                new ObjectParameter("idRDV", typeof(int));
    
            var idMedecinParameter = idMedecin.HasValue ?
                new ObjectParameter("idMedecin", idMedecin) :
                new ObjectParameter("idMedecin", typeof(int));
    
            var confirmeParameter = confirme.HasValue ?
                new ObjectParameter("Confirme", confirme) :
                new ObjectParameter("Confirme", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AddRConfirmation", idRDVParameter, idMedecinParameter, confirmeParameter);
        }
    
        public virtual ObjectResult<SelectConfirmation_Result> SelectConfirmation(Nullable<int> idMedecin)
        {
            var idMedecinParameter = idMedecin.HasValue ?
                new ObjectParameter("idMedecin", idMedecin) :
                new ObjectParameter("idMedecin", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectConfirmation_Result>("SelectConfirmation", idMedecinParameter);
        }
    }
}
