//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DalEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consultation
    {
        public int IDConsultation { get; set; }
        public Nullable<System.TimeSpan> DebutConsulation { get; set; }
        public Nullable<System.TimeSpan> FinConsultation { get; set; }
        public int IDPlanningMED { get; set; }
        public int IDSPecialite { get; set; }
    
        public virtual MEDSpecialite MEDSpecialite { get; set; }
        public virtual PlanningMED PlanningMED { get; set; }
    }
}
