//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DalEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DispoLocal
    {
        public int IDDispo { get; set; }
        public Nullable<System.DateTime> DateIndispo { get; set; }
        public Nullable<System.TimeSpan> HeureDebutIndispo { get; set; }
        public Nullable<System.TimeSpan> HeureFinIndispo { get; set; }
        public int IDLocal { get; set; }
    
        public virtual Locaux Locaux { get; set; }
    }
}
