//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DalEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanningMED
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PlanningMED()
        {
            this.Consultation = new HashSet<Consultation>();
        }
    
        public int IDPlanningMED { get; set; }
        public System.DateTime JourDePressence { get; set; }
        public System.TimeSpan HeureDebutJournee { get; set; }
        public System.TimeSpan HeureFinJournee { get; set; }
        public int IDMedecin { get; set; }
        public int IDMaIsonM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Consultation> Consultation { get; set; }
        public virtual MaisonMedical MaisonMedical { get; set; }
        public virtual Medecin Medecin { get; set; }
    }
}
