//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DalEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class RDVConfirme
    {
        public int IDConfirmation { get; set; }
        public Nullable<int> Confirme { get; set; }
        public int IDMedecin { get; set; }
        public int IDRendezVous { get; set; }
    
        public virtual Medecin Medecin { get; set; }
        public virtual RendezVous RendezVous { get; set; }
    }
}
