//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DalEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class RendezVous
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RendezVous()
        {
            this.RDVConfirme = new HashSet<RDVConfirme>();
        }
    
        public int IDRendezVous { get; set; }
        public string NoRDV { get; set; }
        public int IDPatient { get; set; }
        public int IDPlanningRDV { get; set; }
    
        public virtual Patient Patient { get; set; }
        public virtual PlanningRDV PlanningRDV { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RDVConfirme> RDVConfirme { get; set; }
    }
}
